apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  labels:
    app: game-2048
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
        env: prod
    spec:
      containers:
        - name: game-2048
          image: ghcr.io/cis1912/2048:latest
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: "prod"
          resources:
            limits:
              memory: 512Mi
